USE [master];
GO

ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb2',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb3',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb4',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb5',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb6',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb7',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb8',   SIZE = 1024MB, FILEGROWTH = 256MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'templog', SIZE = 2048MB, FILEGROWTH = 512MB);
GO

-- Alternative Konfiguration bei niedriger Auslastung:
USE [master];
GO

ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdev',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb2',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb3',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb4',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb5',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb6',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb7',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'tempdb8',   SIZE = 512MB, FILEGROWTH = 125MB);
GO
ALTER DATABASE [tempdb] MODIFY FILE (NAME = N'templog', SIZE = 1024MB, FILEGROWTH = 256MB);
GO